### ISSUE TITLE
尝试体验部署该项目过程中遇到的几个问题

### ISSUE THREAD

**Issue by shaneZhang** [cnly1987/nodequery-server#2]
尝试体验了下部署该项目，我发现也并没有传说中的那么难部署。其中我遇到最大的问题是mongodb数据导入上的问题。个人觉得只要仔细完善下文档还是非常不错的。
个人觉得数据库导入文档需要完善下，我个人是到第7步就卡住了，无法进行，10.11.12步骤可以省略，启动项目可以用python manage.py runserver 8888替代。

**Comment by cnly1987** [comment]
> 尝试体验了下部署该项目，我发现也并没有传说中的那么难部署。其中我遇到最大的问题是mongodb数据导入上的问题。个人觉得只要仔细完善下文档还是非常不错的。
> 个人觉得数据库导入文档需要完善下，我个人是到第7步就卡住了，无法进行，10.11.12步骤可以省略，启动项目可以用python manage.py runserver 8888替代。

mongodb不需要导入数据，你只需要创建一个叫nqmonitor的数据库，并且创建该数据库的用户名密码。在setting中配置即可。
第七步卡住，把nodequery-server/servers/migrations/下除了__init__.py的文件全部删除

**Comment by shaneZhang** [comment]
感谢老吴指点，果然是升级一下MongoDB就没问题了，可以在文档中写一下，MongoDB最低支持的版本.多谢。
