### ISSUE TITLE
我用 docker 部署后，static 的文件 修改后 无法生效

### ISSUE THREAD

**Issue by Bravoyk** [cnly1987/nodequery-server#3]
我用 docker 部署后，static 的文件 修改后 无法生效。
我直接进入 docker 容器后， 修改 /app/static/sh/ 下的两个文件里面的 域名，然后发现不生效。。这是为啥。

**Comment by cnly1987** [comment]
静态文件需要设置nginx 代理。
具体配置如下：
server {
   ....,
location /static {
        limit_rate_after 10m; 
	limit_rate 128k;
        #autoindex on;
        alias /home/wwwroot/nqmonitor/static;  //static的绝对路径
	gzip on;
        gzip_types text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;
    }

}
